export const LOAD_TASKS = 'LOAD_TASKS';
export const ADD_TASK = 'ADD_TASK';
export const TOGGLE_TASK_DONE = 'TOGGLE_TASK_DONE';
export const TOGGLE_TASK_IMPORTANT = 'TOGGLE_TASK_IMPORTANT';
export const DELETE_TASK = 'DELETE_TASK';

export const AUTHENTICATED = 'AUTHENTICATED';
export const UnAUTHENTICATED = 'UnAUTHENTICATED';

export const ADD_FORM_VALIDATION_ERROR = 'ADD_FORM_VALIDATION_ERROR';

